---
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
allow-lan: true
autorestart: true
mode: rule
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  listen: 127.0.0.1:7874
  default-nameserver:
  - 114.114.114.114
  - 119.29.29.29
  - 8.8.8.8
  - 8.8.4.4
  - 1.1.1.1
  - 1.0.0.1
  nameserver:
  - 114.114.114.114
  - 119.29.29.29
  - 8.8.8.8
  - 8.8.4.4
  - 1.1.1.1
  - 1.0.0.1
  fallback:
  - https://cloudflare-dns.com/dns-query
  - https://dns.google/dns-query
  - https://1.1.1.1/dns-query
  - tls://8.8.8.8:853
  - tls://dns.rubyfish.cn:853
  - https://1.1.1.1/dns-query
  fallback-filter:
    geoip: true
    ipcidr:
    - 0.0.0.0/8
    - 10.0.0.0/8
    - 100.64.0.0/10
    - 127.0.0.0/8
    - 169.254.0.0/16
    - 172.16.0.0/12
    - 192.0.0.0/24
    - 192.0.2.0/24
    - 192.88.99.0/24
    - 192.168.0.0/16
    - 198.18.0.0/15
    - 198.51.100.0/24
    - 203.0.113.0/24
    - 224.0.0.0/4
    - 240.0.0.0/4
    - 255.255.255.255/32
    domain:
    - "+.google.com"
    - "+.facebook.com"
    - "+.youtube.com"
    - "+.githubusercontent.com"
  fake-ip-filter:
  - "*.lan"
  - time.windows.com
  - time.nist.gov
  - time.apple.com
  - time.asia.apple.com
  - "*.ntp.org.cn"
  - "*.openwrt.pool.ntp.org"
  - time1.cloud.tencent.com
  - time.ustc.edu.cn
  - pool.ntp.org
  - ntp.ubuntu.com
  - ntp.aliyun.com
  - ntp1.aliyun.com
  - ntp2.aliyun.com
  - ntp3.aliyun.com
  - ntp4.aliyun.com
  - ntp5.aliyun.com
  - ntp6.aliyun.com
  - ntp7.aliyun.com
  - time1.aliyun.com
  - time2.aliyun.com
  - time3.aliyun.com
  - time4.aliyun.com
  - time5.aliyun.com
  - time6.aliyun.com
  - time7.aliyun.com
  - "*.time.edu.cn"
  - time1.apple.com
  - time2.apple.com
  - time3.apple.com
  - time4.apple.com
  - time5.apple.com
  - time6.apple.com
  - time7.apple.com
  - time1.google.com
  - time2.google.com
  - time3.google.com
  - time4.google.com
  - music.163.com
  - "*.music.163.com"
  - "*.126.net"
  - musicapi.taihe.com
  - music.taihe.com
  - songsearch.kugou.com
  - trackercdn.kugou.com
  - "*.kuwo.cn"
  - api-jooxtt.sanook.com
  - api.joox.com
  - joox.com
  - y.qq.com
  - "*.y.qq.com"
  - streamoc.music.tc.qq.com
  - mobileoc.music.tc.qq.com
  - isure.stream.qqmusic.qq.com
  - dl.stream.qqmusic.qq.com
  - aqqmusic.tc.qq.com
  - amobile.music.tc.qq.com
  - "*.xiami.com"
  - "*.music.migu.cn"
  - music.migu.cn
  - "*.msftconnecttest.com"
  - "*.msftncsi.com"
  - localhost.ptlogin2.qq.com
  - "+.srv.nintendo.net"
  - "+.stun.playstation.net"
  - xbox.*.microsoft.com
  - "+.xboxlive.com"
  - proxy.golang.org
  - stun.*.*
  - stun.*.*.*
  - heartbeat.belkin.com
  - "*.linksys.com"
  - "*.linksyssmartwifi.com"
  - "+.battlenet.com.cn"
tun:
  enable: true
  stack: gvisor
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
   - tcp://8.8.8.8:53
   - tcp://8.8.4.4:53
experimental:
  interface-name: en0
bind-address: "*"
proxies:
- name: mr.loby.ml1
  server: 95.164.46.235
  port: 2002
  type: vless
  uuid: 18474b7a-ec8f-4409-bc4f-a59116804b86
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: it-full.privateip.net
  network: grpc
  grpc-opts:
    grpc-mode: gun
    grpc-service-name: xray-vless-grpc
  udp: true
proxy-groups:
  - name: mrloby
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
     - mr.loby.ml1
rules:
  - DOMAIN,pay.igamecj.com,mrloby
  - DOMAIN,firebaseremoteconfig.googleapis.com,mrloby
  - DOMAIN,www.napubgm.broker.amsoveasea.com,mrloby
  - DOMAIN,sg.tdatamaster.com ,mrloby
  - DOMAIN,euspeed.igamecj.com,mrloby
  - DOMAIN,kj-se.shadow.igamecj.com,mrloby
  - DOMAIN,meping.igamecj.com,mrloby
  - DOMAIN,sa-sap.shadow.igamecj.com,mrloby
  - DOMAIN,as-hk.shadow.igamecj.com,mrloby
  - DOMAIN,eu-fra.shadow.igamecj.com,mrloby
  - DOMAIN,na-west.shadow.igamecj.com,mrloby
  - DOMAIN,de.voice.gcloudcs.com,mrloby
  - DOMAIN,cloud.gsdk.proximabeta.com,mrloby
  - DOMAIN,2007-shadow.igamecj.com,mrloby
  - DOMAIN,2006-shadow.igamecj.com,mrloby
  - DOMAIN,2008-shadow.igamecj.com,mrloby
  - DOMAIN,2005-shadow.igamecj.com,mrloby
  - DOMAIN,5004-shadow.igamecj.com,mrloby
  - DOMAIN,me-du.shadow.igamecj.com,mrloby
  - DOMAIN,eu-mo.shadow.igamecj.com,mrloby
  - DOMAIN,eu-fra.shadow.igamecj.com,mrloby
  - DOMAIN,eu-mo.shadow.igamecj.com,mrloby
  - DOMAIN,qos.hk.gcloudcs.com,mrloby
  - DOMAIN,pbs.twimg.com,mrloby
  - DOMAIN,platform-lookaside.fbsbx.com,mrloby
  - DOMAIN,api.facebook.com,mrloby
  - DOMAIN,kj-tk.shadow.igamecj.com,mrloby
  - DOMAIN,kj-se.shadow.igamecj.com,mrloby
  - DOMAIN,5005-shadow.igamecj.com,mrloby
  - DOMAIN,sa-sap.shadow.igamecj.com,mrloby
  - DOMAIN,sa-sap-m.shadow.igamecj.com,mrloby
  - DOMAIN,sa-scl.shadow.igamecj.com,mrloby
  - DOMAIN,4006-shadow.igamecj.com,mrloby
  - DOMAIN,3022-shadow.igamecj.com,mrloby
  - DOMAIN,as-in.shadow.igamecj.com,mrloby
  - DOMAIN,as-mb.shadow.igamecj.com,mrloby
  - DOMAIN,as-hk.shadow.igamecj.com,mrloby
  - DOMAIN,as-sg.shadow.igamecj.com,mrloby
  - DOMAIN,3021-shadow.igamecj.com,mrloby
  - DOMAIN,as-sg-m.shadow.igamecj.com,mrloby
  - DOMAIN,1006-shadow.igamecj.com,mrloby
  - DOMAIN,na-mx.shadow.igamecj.com,mrloby
  - DOMAIN,na-centra.shadow.igamecj.com,mrloby
  - DOMAIN,na-east.shadow.igamecj.com,mrloby
  - DOMAIN,na-west.shadow.igamecj.com,mrloby
  - DOMAIN,app.adjust.com,mrloby
  - DOMAIN,hk.voice.gcloudcs.com,mrloby
  - DOMAIN,napubgm.broker.amsoveasea.com,mrloby
  - DOMAIN,idcconfig.gcloudsdk.com,mrloby
  - DOMAIN,k.gjacky.com,mrloby
  - DOMAIN,mgl.lobby.igamecj.com,mrloby
  - DOMAIN,dl.gjacky.com,mrloby
  - DOMAIN,asia.csoversea.mbgame.anticheatexpert.com,mrloby
  - DOMAIN,ig-us-sdkapi.igamecj.com,mrloby
  - DOMAIN,down.anticheatexpert.com,mrloby
  - DOMAIN,ig-us-notice.igamecj.com,mrloby
  - DOMAIN,cloud.vmp.onezapp.com,mrloby
  - DOMAIN,cdn.wetest.qq.com,mrloby
  - DOMAIN,162.62.59.214,mrloby
  - DOMAIN,pu.eazyconqueror.tk,mrloby
  - DOMAIN,astat.bugly.qcloud.com,mrloby
  - DOMAIN,googleads.g.doubleclick.net,mrloby
  - DOMAIN,cloudctrl.gcloudsdk.com,mrloby
  - DST-PORT,80,mrloby
  - DST-PORT,443,mrloby
  - DST-PORT,17500,mrloby
  - DST-PORT,10012,mrloby
  - DST-PORT,10000,mrloby
  - DST-PORT,30000,mrloby
  - DST-PORT,20371,mrloby
  - DST-PORT,5228,mrloby
  - DST-PORT,11395,mrloby
  - DST-PORT,13003,mrloby
  - DST-PORT,15692,mrloby
  - DST-PORT,15656,mrloby
  - DST-PORT,8081,mrloby
  - DST-PORT,8013,mrloby
  - DST-PORT,17000,mrloby
  - DST-PORT,9030,mrloby
  - DST-PORT,2002,mrloby
  - DST-PORT,10132,mrloby
  - DST-PORT,8700,mrloby
  - DST-PORT,18081,mrloby
  - DST-PORT,10276,mrloby
  - DST-PORT,9031,mrloby
  - DST-PORT,8011,mrloby
  - DST-PORT,20000,mrloby
  - DST-PORT,10058,mrloby
  - DST-PORT,10013,mrloby
  - DST-PORT,8088,mrloby
  - DST-PORT,8086,mrloby
  - DST-PORT,27015,mrloby
  - DST-PORT,27030,mrloby
  - DST-PORT,27036,mrloby
  - DST-PORT,27037,mrloby
  - DST-PORT,4380,mrloby
  - DST-PORT,27000,mrloby
  - DST-PORT,27031,mrloby
  - DST-PORT,27036,mrloby
  - DST-PORT,7080,mrloby
  - DST-PORT,8000,mrloby
  - DST-PORT,10012,mrloby
  - DST-PORT,10010,mrloby
  - DST-PORT,10039,mrloby
  - DST-PORT,10096,mrloby
  - DST-PORT,10491,mrloby
  - DST-PORT,10612,mrloby
  - DST-PORT,11455,mrloby
  - DST-PORT,12235,mrloby
  - DST-PORT,13748,mrloby
  - DST-PORT,13894,mrloby
  - DST-PORT,13972,mrloby
  - DST-PORT,20002,mrloby
  - MATCH,mrloby
